---

name: uncrustify_test
on: [push, pull_request]

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  check-uncrustify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake-part-and-tests
        env:
          BADGE: linux
        run: mkdir build;
          cd build;
          cmake -DCMAKE_BUILD_TYPE=Release ..;
          make;
          ../scripts/run_ctest.py


  debug-ninja-uncrustify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: cmake-part-and-tests
        env:
          BADGE: linux
        run: mkdir build;
          cd build;
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..;
          ninja;
          ../scripts/run_ctest.py
